{
 "title": "urlPoller Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rate (R): Number of requests per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_invalid_responses{type=\"failed\"}[1m])) by (route)",
     "legendFormat": "Failed request {{route}}"
    },
    {
     "expr": "sum(increase(http_request_invalid_responses{type=\"invalid\"}[1m])) by (route)",
     "legendFormat": "Invalid request {{route}}"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "Average {{route}}"
    }
   ]
  }
 ]
}